### ISSUE TITLE
Location problems crashing MAS after today's update

### ISSUE THREAD

**Issue by cowboylaw** [tw4449-s-MAS-Submods/tw4449-Custom-Room-Selection-Pack-Main-Repository#42] opened 2022-07-18 17:34 UTC
Error text on launch is:

[code]
I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/submods/location_selector/Locatons/garden-view.rpy", line 210, in script
    init 30 python:
  File "game/submods/location_selector/Locatons/garden-view.rpy", line 272, in <module>
    store.mas_cardgames._m1_zz_cardgames__scanDeskSprites()
AttributeError: 'StoreModule' object has no attribute 'mas_cardgames'

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/submods/location_selector/Locatons/garden-view.rpy", line 210, in script
    init 30 python:
  File "D:\DDLC MAS\renpy\ast.py", line 814, in execute
    renpy.python.py_exec_bytecode(self.code.bytecode, self.hide, store=self.store)
  File "D:\DDLC MAS\renpy\python.py", line 1719, in py_exec_bytecode
    exec bytecode in globals, locals
  File "game/submods/location_selector/Locatons/garden-view.rpy", line 272, in <module>
    store.mas_cardgames._m1_zz_cardgames__scanDeskSprites()
AttributeError: 'StoreModule' object has no attribute 'mas_cardgames'

Windows-8-6.2.9200
Ren'Py 6.99.12.4.2187
Monika After Story 0.12.8
[/code]

Hoping there's an easy solution for this!  Thanks!

**Comment by multimokia** [comment] 2022-07-19 15:43
Update MAS to 0.12.9, the release notes state it requires at least MAS 0.12.9

**Comment by multimokia** [comment] 2022-07-19 16:33
[Closing as not a bug]

**Closed by multimokia** 2022-07-19 16:33 UTC
